### ISSUE TITLE
Unofficial MusicXML test suite

### ISSUE THREAD

**Issue by rvilarl** [stringsync/vexml#26] opened 2022-04-13 06:23 UTC
Look at that http://lilypond.org/doc/v2.20/input/regression/musicxml/collated-files.html

It is also in https://github.com/0xfe/vexflow/issues/519 wher Mohit commented on EasyScore

**Comment by jaredjj3** [comment] 2022-04-13 19:24
This is a great find! I'll add this to the examples and see what breaks if you haven't already.

**Comment by rvilarl** [comment] 2022-04-13 20:53
Perhaps we should decide on what elements to add on basis of chapters ie: 
01 pitches

I would suggest to follow the actual order which seems to be quite logical. :)

**Comment by jaredjj3** [comment] 2022-04-14 10:15
I agree with following the order. I was able to add most of the test suite to `@stringsync/musicxml` ([link](https://github.com/stringsync/musicxml/blob/3e6a65fde5aa46bf7fa9b7df28836d6632ece3bc/src/examples/manifest.ts#L376)). It exposed a lot of broken features, but I was able to fix them. I also updated the test suite to MusicXML version 4.0. I skipped or fixed intentionally broken files.

I'll make a PR to add the examples to this library.

**Comment by jaredjj3** [comment] 2022-04-14 10:30
A lot of them render something, but it's hard to say if they're right or not.

![image](https://user-images.githubusercontent.com/19232300/163365728-60518c1c-7ee3-4d35-90c2-80bdae8af228.png)

I'm going to create a `reference` directory that will have a bunch of static images in it that correspond to the examples. They should serve as a "gold standard" and allow us as humans to compare the results. I'm reluctant to use something as precise as an image diff because the [test suite states](http://lilypond.org/doc/v2.20/input/regression/musicxml/collated-files.html):

>the output is not supposed to be used as a definitive reference rendering, but rather as an indication how one particular application supports and interprets each of the test files.

I'm also going to improve the results page and make it easier to view examples. I don't want the extra tests to distract you, so I will make a PR after I address the DX issues with adding these examples.

**Comment by rvilarl** [comment] 2022-04-14 18:16
I am also making changes to make things work.

**Comment by rvilarl** [comment] 2022-04-14 22:26
I added all my fixes to #25. It would be nice to merge it :)

**Closed** 2022-04-15 12:31 UTC
